version: 1.0.{build}
image: Ubuntu1804

services:
- docker

init:
- docker run -d -p 6379:6379 --rm redislabs/redisgraph:latest

build:
  project: NRedisGraph.sln
  publish_nuget: false
  verbosity: minimal